name: Build and deploy Node.js app to Azure Web App - ridenitt-web

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js version
        uses: actions/setup-node@v3
        with:
          node-version: "22.x"

      - name: npm install, prisma generate, build, and test
        run: |
          npm install
          npx prisma generate
          npm run build --if-present
          npm run test --if-present

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: node-app
          path: |
            dist
            prisma
            package.json
            package-lock.json

  deploy:
    runs-on: ubuntu-latest
    needs: build
    permissions:
      id-token: write
      contents: read

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: node-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_4006BF6D9A9A4BF9850F43C4A84F788E }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_394F8B041DC447C09F2B7E9373C7DBB0 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_A4DBB7CAA516434EB60FAFF2D1812F0A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: ridenitt-web
          slot-name: Production
          package: .
